### ISSUE TITLE
Asset ViewHelper doesn't work in TYPO3 backend modules correctly

### ISSUE THREAD

**Issue by mediaessenz** [s2b/vite-asset-collector#35] opened 2024-01-14 20:32 UTC
In vite serve mode, css is working, but included fonts not.

In my case I have a backend module js (users.js) which imports a backend-module.scss like so:
import './styles/backend-module.scss';

This scss imports a font like so:
@import 'bootstrap-icons/font/bootstrap-icons';

If I include it in my backend module like so, all icons are missing:
<vac:asset.vite entry="build/frontend/intern/backend/users.js" />

The js and css is correct.

But if I build all things (vite build) and set extension setting useDevServer to 0, only the js code is working correctly.
Css and fonts are missing.

**Comment by mediaessenz** [comment] 2024-01-14 21:42
I fixed the icon font problem by moving the bootstrap icon import directly into the users.js like so:
import 'bootstrap-icons/font/bootstrap-icons.scss';

But importing my own stylesheets still not work in final build.

If I add for eg. this css in my backend-module.scss, it has no effect in the final build:
body { background-color: red; }

if I switch useDevServer to 1, the background becomes red.

**Comment by s2b** [comment] 2024-01-14 21:52
Hi! There is a problem with relative path resolution in scss files in vite itself. I found two possible resolutions and described them here:

https://github.com/s2b/vite-asset-collector/issues/17#issuecomment-1810833288

Hope this helps.

**Comment by mediaessenz** [comment] 2024-01-14 22:13
I already read this issue and do not think it's the same.
I tested it with a css file as well and have exact the same problem.

Also tried to define a resolve.alias in my vite.config.js like so:
resolve: {
		alias: [
			{ find: '@backend', replacement: fileURLToPath(new URL('./build/frontend/intern/backend', import.meta.url)) },
		],
	},


.. and using it in the import of my users.js:
import "@backend/styles/test.css"

**Comment by s2b** [comment] 2024-01-14 22:19
Can you reproduce your issues in frontend context? Are there any errors in the browser console?

**Comment by mediaessenz** [comment] 2024-01-14 22:24
No, frontend build and serve works without any errors.

**Comment by s2b** [comment] 2024-01-14 22:57
Ok, then I'll need to look into backend integration next. Can you give some details of how you attempt to add the assets to the backend?

**Comment by mediaessenz** [comment] 2024-01-15 10:18
Is there another way to get the generated css into the backend beside using the viewhelper?

**Comment by mediaessenz** [comment] 2024-01-15 10:35
FYI:
I checked the generated manifest file for the css and found this entry:
```
  "_backend-module-!~{00E}~.js": {
    "file": "assets/backend-module-9Bzn9MtR.css",
    "src": "_backend-module-!~{00E}~.js"
  },
  "_backend-module-rt5IyfjD.js": {
    "assets": [
      "assets/bootstrap-icons-bb42NSi8.woff2",
      "assets/bootstrap-icons-TqycWyKO.woff"
    ],
    "css": [
      "assets/backend-module-9Bzn9MtR.css"
    ],
    "file": "assets/backend-module-rt5IyfjD.js",
    "imports": [
      "_bootstrap-vue-next-temHq8v8.js"
    ]
  },
```
If i add the generated in my backend module manuallly liks so, everthing looks good:
```
<f:be.pageRenderer includeCssFiles="{0:'/_assets/vite/assets/backend-module-9Bzn9MtR.css'}" />
```

**Comment by mediaessenz** [comment] 2024-01-15 11:23
New findings:
The generated manifest file also contains this part:
```
  "build/frontend/intern/backend/users.js": {
    "css": [
      "assets/users-E_a7VHbY.css"
    ],
    "file": "assets/users-uK7zxSrT.js",
    "imports": [
      "_bootstrap-vue-next-temHq8v8.js",
      "_vue-multiselect.esm-6o1xCtNy.js",
      "_backend-module-rt5IyfjD.js"
    ],
    "isEntry": true,
    "src": "build/frontend/intern/backend/users.js"
  },
```
If I check the assets/users-E_a7VHbY.css file, it doesn't contains the imported scss/css code!

**Comment by s2b** [comment] 2024-01-15 11:34
The problem is that there are several places and methods to inject frontend code into the backend. I guess I'll have to look into each method to find a solution that works in all cases.

In the Slack channel there was a discussion recently where someone wanted to add css/js to the backend. In the end, he created a middleware and used ViteService there. However, I haven't tested this myself yet.

**Comment by mediaessenz** [comment] 2024-01-15 11:47
I think it is exact this "issue": https://github.com/vitejs/vite/issues/15161

**Comment by mediaessenz** [comment] 2024-01-15 12:19
Meanwhile I found a workaround, by moving all css/scss imports to a separate file and add an own entrypoint to it.

backendStyles.js:
```
import '@backend/styles/backend-modules.scss'
// ... further scss/css imports
```

```
const VITE_ENTRYPOINTS = [
	"build/frontend/intern/backend/backendStyles.js",
	"build/frontend/intern/backend/users.js",
];
```
... and add them both into my backend module like so:
```
	<vac:asset.vite entry="build/frontend/intern/backend/backendStyles.js" />
	<vac:asset.vite entry="build/frontend/intern/backend/users.js" />
```

**Comment by s2b** [comment] 2024-01-17 15:32
After our conversation via Slack, I'll close this issue and open a new one for the concrete issue: #36

**Closed by s2b** 2024-01-17 15:32 UTC
